const fs = require('fs');
const path = require('path');
const file = process.argv[2] || 'supabase/migrations/20251120_all_migrations_gap_fix.sql';
const p = path.resolve(process.cwd(), file);
const s = fs.readFileSync(p, 'utf8');
const bak = p + '.replacetypes.block.backup';
fs.writeFileSync(bak, s);
console.log('Backup written to', bak);
const regex = /CREATE\s+TYPE\s+routine_step_type[\s\S]*?CREATE\s+TYPE\s+autism_routine_rigidity\s+AS\s+ENUM\s*\([\s\S]*?\);/gi;
let match;
let count = 0;
let out = s.replace(regex, function(m){ count++; return `-- Canonical enums block replaced (original preserved in backup)\nCREATE TYPE routine_step_type AS ENUM ('routine', 'flexZone', 'note');\nCREATE TYPE transition_cue_type AS ENUM ('text', 'audio', 'visual', 'mixed');\nCREATE TYPE freeform_data_type AS ENUM ('note', 'sketch');\nCREATE TYPE step_execution_status AS ENUM ('pending', 'active', 'paused', 'completed', 'skipped');\nCREATE TYPE timer_notification_type AS ENUM ('visual', 'audio', 'vibration', 'all');\nCREATE TYPE timer_intensity AS ENUM ('subtle', 'normal', 'prominent');\nCREATE TYPE neurotype_time_awareness AS ENUM ('high', 'medium', 'low');\nCREATE TYPE autism_routine_rigidity AS ENUM ('flexible', 'structured', 'strict');\n`; });
fs.writeFileSync(p, out, 'utf8');
console.log('Replaced', count, 'occurrences of the types block.');
process.exit(0);
